import Head from "next/head";
import { CodingContent } from "../components/CodingContent";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CodingContent />
    </>
  );
}

//todo
// make images on house of child have loader
//maybe make a loading skeleton?
// make genaric image component
//update 3d art content page to have small thumbnails
//update painting section to have small version of pictures
// add demo reel to 3d art content page
//make radix slider
//make radix full screen image viewer
//about page animation make it landing page?
//font
//vercel and store images in s3 and cloudfron?
// or vercel and store images in google soltuion to make a project saying i wanted to learn google products?
//no text cursor
//favicon
//add link to name so it links back to index
